services:
  app:
    build: .
    volumes:
      - .:/app  # Mount the current directory to the container
    ports:
      - "8000:8000"
      - "8081:8081"
      - "8083:8083"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
